[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "The TIMES Ireland Model (TIM)"
authors = [{name = "EPMG group", email = "bsuleimenov@ucc.ie"}]
dynamic = ["version", "description"]
